GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlck5hbWUiOiJraGFuaG5vaSIsImlhdCI6MTYxNTk5Mzc4NiwiZXhwIjoxNjE1OTkzODQ2fQ.TObwdV0Qru5bnufjtAiodsHklM_Y_uGNdET9ITmHUkY

###
POST http://localhost:5000/login
Content-Type:  application/json

{
    "userName": "khanhnoi"
}

###
POST http://localhost:5000/token
Content-Type:  application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlck5hbWUiOiJraGFuaG5vaSIsImlhdCI6MTYxNTk5NTcwNiwiZXhwIjoxNjE1OTk5MzA2fQ.VAT0v1uJjqi3bTA2At0zUxENgNw2604CXJkLiZ8S_Eg"
}

###
DELETE  http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlck5hbWUiOiJraGFuaG5vaSIsImlhdCI6MTYxNTk5Mzc4NiwiZXhwIjoxNjE1OTkzODQ2fQ.TObwdV0Qru5bnufjtAiodsHklM_Y_uGNdET9ITmHUkY

